name: untitled2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+3
  path: ^1.8.0
  intl: ^0.17.0
  provider: ^6.0.0
  path_provider: ^2.0.0

  # Remove sqflite_ffi if you are not targeting desktop
  # sqflite_ffi: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
